### ISSUE TITLE
Thanks for your askubuntu answer on how to fix a python3.5 installation

### ISSUE THREAD

**Issue by devonhk** [darkerego/pysslShells#1]
Hey, I just wanted to say thanks for the solution you posted here https://askubuntu.com/a/1034266/829985 . I would have spent quite a bit of time looking into the issue had I not found your answer.

I didn't have any other way of messaging you, so I just picked one of your repos.
I'll make sure to close this ticket so I don't pollute the repo.

**Comment by darkerego** [comment]
You are very welcome, glad I could help!
